## Numpy Assignment

01. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [40]:
def custFunction(a,n):
    a = np.array(a).reshape(-1,1)
    b = np.array(range(n-1,-1,-1))
    return np.matrix(a**b)

print(custFunction(range(1,5), 4))

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


02. Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [94]:
def custFunction(a, k):
    if k>0:
        li = []
        seq = len(a)-k+1
        for x in range(seq):
            d=0
            c = a[x:x+k]
            for elem in c:
                d+=elem
            d = d/k
            li.append(d)
        return li

In [95]:
print('Example', '-'*60)
print(custFunction(np.arange(10,110, 10), 4))

Example ------------------------------------------------------------
[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


In [96]:
print('Final Answer', '-'*60)
print(custFunction([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3))

Final Answer ------------------------------------------------------------
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
